global:
  image:
    name: mysql
    tag: 5.7
  ## @param deploymentType Mysql databse deployment type (`deployment` or `statefulset`)
  ##  
  deploymentType: deployment

nameOverride: ""

deployment:


statefulset: