apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "easyclaim-backend.fullname" . }}
  labels:
    {{- include "easyclaim-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      {{- include "easyclaim-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "easyclaim-backend.fullname" . }}
      labels:
        {{- include "easyclaim-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name:  {{ .Chart.Name }}
          image: "{{ .Values.global.image.name }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: "/config"
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "600Mi"
              cpu: "400m"
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "easyclaim-backend.fullname" . }}
          items:
          - key: application
            path: application.properties
