apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "easyclaim-backend.fullname" . }}
  labels:
    {{- include "easyclaim-backend.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "easyclaim-backend.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
