apiVersion: v1
entries:
  easyclaim:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-07-22T23:57:41.32083193+05:30"
    dependencies:
    - name: easyclaim-frontend
      repository: https://devopspilot.com/helm/charts
      version: 1.0.0
    - name: easyclaim-backend
      repository: https://devopspilot.com/helm/charts
      version: 1.0.0
    - name: mysql
      repository: https://devopspilot.com/helm/charts
      version: 1.0.0
    description: Helm chart for deploying Easyclaim application
    digest: 9b522fba6447363a71ca401d2113737dd5b2b6ace3a5d06a712ecb8f55559bd3
    name: easyclaim
    urls:
    - https://devopspilot.com/helm/charts/easyclaim-1.0.0.tgz
    version: 1.0.0
  easyclaim-backend:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-07-22T23:57:41.322821779+05:30"
    description: Helm chart for deploying Easyclaim backend application
    digest: 89756f653ddc3a07f7a4b58c3eac675c3632f5c00aa64c5fb01389dcc5ed06fd
    name: easyclaim-backend
    urls:
    - https://devopspilot.com/helm/charts/easyclaim-backend-1.0.0.tgz
    version: 1.0.0
  easyclaim-frontend:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-07-22T23:57:41.324805039+05:30"
    description: Helm chart for deploying Easyclaim frontend application
    digest: 6912ca3017c322971e40c7198ec661aabda5d418f612c893762cfc433197d6cc
    name: easyclaim-frontend
    urls:
    - https://devopspilot.com/helm/charts/easyclaim-frontend-1.0.0.tgz
    version: 1.0.0
  kubectl:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-07-22T23:57:41.325432165+05:30"
    description: Helm chart for running kubectl docker container
    digest: a04ffbb2a950c2c5bf51b47c586da7c6e935880ede786d1743c0582b492eb163
    name: kubectl
    urls:
    - https://devopspilot.com/helm/charts/kubectl-0.0.1.tgz
    version: 0.0.1
  mysql:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-07-22T23:57:41.327608267+05:30"
    description: Helm chart for running mysql database
    digest: 4712df753b8d71c64015b2fcb1b02011dce01dbb19fb7295e0eb5405352948fe
    name: mysql
    urls:
    - https://devopspilot.com/helm/charts/mysql-1.0.0.tgz
    version: 1.0.0
  voting-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-07-22T23:57:41.328216373+05:30"
    description: A Helm chart for Kubernetes
    digest: cf3c37f1b79d88d7bf8cea1f677c6ac4bfcc4c37f6856e392cf54d5b6e486c5f
    name: voting-app
    type: application
    urls:
    - https://devopspilot.com/helm/charts/voting-app-0.1.1.tgz
    version: 0.1.1
generated: "2021-07-22T23:57:41.31373471+05:30"
