global:
  image:
    name: vigneshsweekaran/easyclaim-backend
    tag: latest
  replicas: 2
  databaseServiceName: mysql

nameOverride:

service:
  type: NodePort
  nodePort: 32012

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

postInstall:
  username: test
  password: test
  firstName: test
  lastName: test
  age: 25
  salary: 50000
