kind: ConfigMap 
apiVersion: v1 
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "easyclaim-frontend.fullname" . }}
  labels:
    {{- include "easyclaim-frontend.labels" . | nindent 4 }}
data:
  config: |-
    {
      "authConfig": {
        "backendUrl": "http://{{ .Values.configmap.backendUrl }}:{{ .Values.configmap.backendPort }}"
      }
    }
