kind: ConfigMap 
apiVersion: v1 
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    name: easyclaim-frontend
data:
  config: |-
    {
      "authConfig": {
        "backendUrl": "{{ .Values.configmap.backendUrl }}"
      }
    }
