apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "easyclaim-frontend.fullname" . }}
  labels:
    {{- include "easyclaim-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      {{- include "easyclaim-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "easyclaim-frontend.fullname" . }}
      labels:
        {{- include "easyclaim-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name:  {{ .Chart.Name }}
          image: "{{ .Values.global.image.name }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: Always
          volumeMounts:
          - name: config-volume
            mountPath: "/usr/share/nginx/html/assets"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "easyclaim-frontend.fullname" . }}
          items:
          - key: config
            path: config.json
