apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    name: easyclaim-frontend
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      name: easyclaim-frontend
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        name: easyclaim-frontend
    spec:
      containers:
        - name:  {{ .Release.Name }}
          image: "{{ .Values.global.image.name }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: Always
          volumeMounts:
          - name: config-volume
            mountPath: "/usr/share/nginx/html/assets"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}
          items:
          - key: config
            path: config.json
