apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "easyclaim-frontend.fullname" . }}
  labels:
    {{- include "easyclaim-frontend.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32011
  selector:
    {{- include "easyclaim-frontend.selectorLabels" . | nindent 4 }}
  type: NodePort
