{{- if (eq "statefulset" .Values.global.deploymentType) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: local

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "mysql.fullname" . }}-1
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "mysql.fullname" . }}-2
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "mysql.fullname" . }}-3
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data3"
{{- end }}
