apiVersion: v2
name: easyclaim
version: 1.0.0
description: Helm chart for deploying Easyclaim application
appVersion: 1.0.0

dependencies:
  - name: easyclaim-frontend
    version: 1.0.0
    repository: https://devopspilot.com/helm/charts
  - name: easyclaim-backend
    version: 1.0.0
    repository: https://devopspilot.com/helm/charts
  - name: mysql
    version: 1.0.0
    repository: https://devopspilot.com/helm/charts

