global:
  image:
    image: vigneshsweekaran/easyclaim-frontend
    tag: 32011
  replicas: 2

service:
  type: NodePort
  nodePort: 32011

hpa:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50