global:
  image:
    name: vigneshsweekaran/easyclaim-frontend
    tag: 32011
  replicas: 2

service:
  type: NodePort
  nodePort: 32011

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50