global:
  image:
    name: vigneshsweekaran/easyclaim-frontend
    tag: latest
  replicas: 2

service:
  type: NodePort
  nodePort: 32011

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

configmap:
  backendUrl: http://192.68.0.0:32012