{{- if (eq "deployment" .Values.global.deploymentType) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.global.image.name }}:{{ .Values.global.image.tag }}"
        name: {{ .Chart.Name }}
        envFrom:
        - secretRef:
            name: {{ include "mysql.fullname" . }}
        - configMapRef:
            name: {{ include "mysql.fullname" . }}
        ports:
        - containerPort: 3306
          name: {{ .Chart.Name }}
{{- end }}
