{{- if (eq "deployment" .Values.global.deploymentType) }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
{{- end }}