{{- if (eq "deployment" .Values.global.deploymentType) }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  ports:
  - port: 3306
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
{{- end }}